development:
  adapter: postgresql
  host: localhost
  username: dioud
  database: iqn


production:
  adapter: postgresql
  host: localhost
  username: root
  password: hcjJfUtsQSQW1s4j
  database: iqn